version: '3.3'
services:
    rtsp_server_live555:
        container_name: rtsp_server_live555
        image: rtsp_server_live555
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "8080:80"
        - "554:554"
        volumes:
        - ./data:/data
        restart: always